openapi: 3.0.0
info:
  title: Simple API
  version: '1.0'
paths:
  /api/v1/auth:
    post:
      summary: "User authorization"
      operationId: "userAuthorization"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: "Authorization success."
        '401':
          description: "Authorization failed."
  /api/v1/register:
    post:
      summary: "Register user"
      operationId: "userRegister"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
                - email
                - name
                - password
                - role
      responses:
        '201':
          description: "Registration success."
        '401':
          description: "Registration failed."
  /api/v1/logout:
    get:
      summary: "Logout user"
      operationId: "userLogout"
      security:
        - bearerAuth: []
      responses:
        '201':
          description: "Registration success."
        '401':
          description: "Registration failed."
  /api/v1/profile/{id}:
    get:
      summary: "User profile"
      operationId: "userProfile"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: integer

      responses:
        '201':
          description: "Ok."
        '401':
          description: "Not found."
  /api/v1/postman/auth:
    get:
      summary: "Postman auth"
      operationId: "authPostman"
      responses:
        '201':
          description: "Ok."
        '401':
          description: "Invalid token"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer